"""Python translation of
`reference_code/1_Portfolio_Creation/LongShort_Decile_Portfolio_Creation/Generate Decile Portfolios.R`.

For each characteristic, build 5 quintile portfolios per month (value-weighted),
subtract risk-free, write raw and excess CSVs.
"""

import os

import numpy as np
import pandas as pd

from src.code import utils
from src.code.dplyr_shim import ntile


# R defines: feats = c('LME',...,'LTurnover'); y_min = 1963; y_max = 2016.
# Note: Y_MIN here is 1963 (differs from utils.Y_MIN=1964) — matches the R script.
FEATS = utils.FEATS_LIST
Y_MIN = 1963
Y_MAX = 2016


def remove_rf(port_ret, factor_path):
    """risk free rate from Fama French website."""
    file_nm = os.path.join(factor_path, "rf_factor.csv")
    r_f = pd.read_csv(file_nm, header=None).iloc[:, 0].values.astype(float)
    for i in range(port_ret.shape[1]):
        port_ret[:, i] = port_ret[:, i] - r_f / 100
    return port_ret


def main(feats=FEATS, y_min=Y_MIN, y_max=Y_MAX,
         data_chunk_path=utils.DATA_CHUNK_DIR,
         output_path=utils.PY_QUINTILE_PORT_DIR,
         factor_path=utils.FACTOR_DIR):
    os.makedirs(output_path, exist_ok=True)

    for f in range(len(feats)):
        print(feats[f])
        deciles = np.full((648, 5), np.nan)
        for year in range(y_min, y_max + 1):
            print(year)
            # same yearly data files as generated by tree portfolios
            data = pd.read_csv(
                os.path.join(data_chunk_path, feats[f], f"y{year}.csv")
            )

            for month in range(1, 13):
                i = 12 * (year - y_min) + month  # R 1-indexed
                ymmask = data["mm"] == month
                retm = data.loc[ymmask, "ret"].astype(float).values
                feature_m = data.loc[ymmask, feats[f]].astype(float).values
                size_m = data.loc[ymmask, "size"].astype(float).values

                groups = ntile(feature_m, 5)

                for j in range(1, 6):
                    mask_j = groups == j
                    s_j = size_m[mask_j]
                    total = s_j.sum()
                    if total != 0:
                        w = s_j / total
                        deciles[i - 1, j - 1] = np.dot(retm[mask_j], w)
                    else:
                        deciles[i - 1, j - 1] = np.nan

        col_names = [f"{feats[f]}.{j}" for j in range(1, 6)]
        deciles_df = pd.DataFrame(deciles, columns=col_names)

        # R: deciles_excess = remove_rf(deciles[13:648,], factor_path) — rows 13..648 (R 1-indexed)
        deciles_trimmed = deciles[12:648, :].copy()
        deciles_excess = remove_rf(deciles_trimmed, factor_path)
        deciles_excess_df = pd.DataFrame(deciles_excess, columns=col_names)

        deciles_df.to_csv(
            os.path.join(output_path, f"{feats[f]}.csv"), index=False
        )
        deciles_excess_df.to_csv(
            os.path.join(output_path, f"{feats[f]}_excess.csv"), index=False
        )


if __name__ == "__main__":
    main()
